runtime: php55
api_version: 1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1 
  min_pending_latency: 500ms
  max_pending_latency: automatic

handlers:
- url: /backendscripts/dlsites.php
  script: dlsites.php
- url: /backendscripts/crashreport.php
  script: crashreport.php
- url: /backendscripts/docsites.php
  script: docsites.php
- url: /backendscripts/processdlstats.php
  script: processdlstats.php
